name: Cache Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: prime-cache-c4418d3
        id: prime-cache-c4418d3
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-c4418d3

      - name: echo-cache-result
        shell: bash
        run: |
          echo "Cache hit result: ${{ steps.prime-cache-c4418d3.outputs.cache-hit }}"

      - name: Done
        run: echo "Workflow completed successfully!"
